
import {Providers} from '../providers';
import {getTranslations} from 'next-intl/server';
import MainLayout from '@/components/layout/MainLayout'
import '../globals.css'
import localFont from 'next/font/local'

export async function generateMetadata({params: {lang}}: {params: {lang: string}}) {
  const t = await getTranslations({locale: lang, namespace: 'Metadata'});

  return {
    title: t('title'),
    description: t('description'),
  };
}

const fancyCut = localFont({
  src: '../../public/fonts/Fancy Cut Pro.ttf',
  variable: '--fancy',
})

const brilliantCut = localFont({
  src: '../../public/fonts/Brilliant Cut Pro.ttf',
  variable: '--brilliant',
})


export default async function LocaleLayout({
  children,
  params: {lang}
}: {
  children: React.ReactNode;
  params: {lang: string};
}) {
  const messages = (await import(`../../public/locales/${lang}.json`)).default;


  return (
    <html lang={lang} dir={lang === 'ar' ? 'rtl' : 'ltr'} className={`${fancyCut.variable} ${brilliantCut.variable}`}>
      <body className='w-[100%]'>
        <Providers locale={lang} messages={messages}>
          <MainLayout>
          {children}
          </MainLayout>
        </Providers>
      </body>
    </html>
  );
}










// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import {Providers} from '../providers';

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
//   params:{lang}
// }: Readonly<{
//   children: React.ReactNode;
//   params:{lang:string}
// }>) {
//   return (
//     <html lang={lang} dir={lang ==='ar'? 'rtl' : 'ltr'}>
//       <body className={inter.className}>
//         <Providers>
//           {children}
//         </Providers>
//       </body>
//     </html>
//   );
// }
